### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by taxegypt** [TomasVotruba/unused-public#57]
```bash
Invalid configuration:
Unexpected item 'parameters › unused_public › template_paths'.
```

```yaml
parameters:
  // ...
  unused_public:
    methods: true
    properties: true
    constants: true
    template_paths:
        - Modules/*/views
```

also do i need to install https://github.com/TomasVotruba/bladestan ?
